#!/usr/bin/env sh

sed 's|${which-unsplash-so-fancy}|'`which unsplash-so-fancy`'|g' './unsplash-so-fancy.plist' > ~/Library/LaunchAgents/unsplash-so-fancy.plist
launchctl unload ~/Library/LaunchAgents/unsplash-so-fancy.plist
launchctl load ~/Library/LaunchAgents/unsplash-so-fancy.plist
unsplash-so-fancy
